version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    api:
        build:
            context: ./server
        environment:
            # Redis database
              image: redis
            
            # Postgres database
              image: postgres
              environment: PGPASSWORD=postgres_password
          # API Server
            api:
              depends_on:
                 - redis
                 - postgres
              build: ./server 
              image: ravimprala/complex_api

            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432 

            # Worker Service
            worker: 
                  build: ./worker
                  image: ravimprala/complex_worker
                  environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            # Client
              client: 
                  build: ./client
                  image: ravimprala/complex_client
            # Nginx
              nginx:
              depends_on:
              - api
              - client
              restart: always
              build: 
              context: ./nginx
              ports:
                    "3050:80"